apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: franklin-mt-service
  namespace: franklin-mt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: franklin-mt-service
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: franklin-mt-service
  namespace: franklin-mt
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: franklin-mt-service
