apiVersion: v1
kind: Secret
metadata:
  name: franklin-mt-service-secrets
  namespace: franklin-mt
type: Opaque
stringData:
  AZURETRANSLATOR__KEY: replace-via-key-vault
  AZURETRANSLATOR__REGION: replace-with-resource-region
