apiVersion: v1
kind: Service
metadata:
  name: franklin-mt-service
  namespace: franklin-mt
spec:
  selector:
    app.kubernetes.io/name: franklin-mt-service
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
