<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Franklin.MtService</RootNamespace>
    <AssemblyName>Franklin.MtService</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Update="openapi.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
